version: '3'

services:
  todo:
    image: agate/todo/server/go
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - TODO_HOST=0.0.0.0
      - TODO_PORT=8080
      - GIN_MODE=debug # use "release" mode in production
